# Generated by Django 2.1.7 on 2019-02-20 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=24)),
                ('eadd', models.TextField()),
                ('dob', models.DateTimeField(default=datetime.datetime(2019, 2, 20, 12, 49, 37, 958616, tzinfo=utc))),
            ],
        ),
    ]
