# Generated by Django 2.1.7 on 2019-03-07 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReshApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworksModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10)),
                ('snmae', models.CharField(max_length=30)),
                ('doj', models.DateTimeField(default=datetime.datetime(2019, 3, 7, 4, 49, 6, 923841, tzinfo=utc))),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
            ],
        ),
        migrations.AlterField(
            model_name='emp',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 4, 49, 6, 923841, tzinfo=utc)),
        ),
    ]
