# Generated by Django 2.1.7 on 2019-03-11 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReshApp', '0002_auto_20190307_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworksModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10)),
                ('snmae', models.CharField(max_length=30)),
                ('doj', models.DateTimeField(default=datetime.datetime(2019, 3, 11, 13, 7, 6, 113485, tzinfo=utc))),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
            ],
        ),
        migrations.DeleteModel(
            name='NetworksModule',
        ),
        migrations.AlterField(
            model_name='emp',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 13, 7, 6, 113485, tzinfo=utc)),
        ),
    ]
